# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 90754ea2054de41dccff8913371def47bde926213a3a4aed2e7bb9f87b3b153370d83b77c69e41b01755509a1629bde9a0abb0c3dedebfd16cb39e1b217ae5a9

test:
  secret_key_base: 7accf801b797fb487b4e7c252863ce631394b45f10fd77a0fe51fafc1483d6979b75abd51ed75a827b5f8019a653ef796acd3128cadc6d15188f4c9f275b2303

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
